ai-projects:
  title: "AI Projects"

automation:
  title: "Automation"

operations:
  title: "Operations"

data:
  title: "Data"

software-implementations:
  title: "Software Implementations"

security:
  title: "Security"

speaking:
  title: "Speaking"